### PR TITLE
Added some more branding combinations :)

### PR DESCRIPTION
**Pull request by hyarsan**
These are all compressed into an 7z to save storage space. Some combinations may be missing though.

### CODE REVIEW

**Comment by RobLoach** [comment]
Don't think compression is needed. Imgur may be a good place for these. This is a place for just the assets, not the combined assets.

**Comment by hyarsan** [comment]
I agree, there is no point in these "bigger" RetroArch logos anyway! :)

**Comment by orbea** [comment]
If and when this PR is merged, please rebase it so the commit with the now deleted archive doesn't exist. That would be unfortunate to add to the git history.

**Comment by hyarsan** [comment]
I don't really know how to do that, I am still pretty new to GitHub. Do I need to delete my fork and refork retroarch-assets and make an new pull request without the archive in it? I don't know how to push, this is all new to me. I do know that the edited branding images look much nicer and even have them as my wallpaper :)

**Comment by hyarsan** [comment]
Now that Alcaro flattend this repository, how do you properly do this?

**Comment by Alcaro** [comment]
...what, I thought GitHub would just automatically redirect the PRs to the new HEAD.

Rebase and open a new PR. Sorry for the inconvenience, I thought GitHub was a bit smarter than that.

**Pull request closed without merging**
