### PR TITLE
Add Arabic, Chinese and Korean fallback font

### PR DESCRIPTION
**Pull request by guoyunhe**
None of fonts from asses support Arabic, Chinese and Korean properly. So I made a PR to add these fallback fonts.

Then in MaterialUI, OZONE and XMB menu driver, let RetroArch use fallback fonts when these languages are set. See https://github.com/libretro/RetroArch/pull/10699

Result:

Korean fallback font: Sunflower
Screenshot_20200524_171042
Screenshot_20200524_173658

Chinese fallback font: Droid Sans Fallback
Screenshot_20200524_155722

Arabic fallback font: DejaVu Sans
Screenshot_20200524_170956

### CODE REVIEW

**Comment by RobLoach** [comment]
Is there a license behind Droid Sans Fallback? Do we need to include the license or a readme for it?

**Comment by guoyunhe** [comment]
According to Wikipedia, it is Apache License. I didn't see any license files for other fonts. So maybe we don't need to include the license file but mention the copyright and license info in the README.

**Comment by guoyunhe** [comment]
Not yet. If this idea is liked, I can work on it soon.

**Comment by NewUserHa** [comment]
could it choose a beautiful font instead of just make the font working?

**Comment by guoyunhe** [comment]
The fonts need to FOSS licensed and supported by RetroArch. The plan is to make the font work first. Then if someone finds a better font, it can be easily replaced.

**Comment by NewUserHa** [comment]
Source Han Sans?

**Comment by guoyunhe** [comment]
Source Han Sans doesn't have a single file that covers all CJK and is supported by RetroArch.

Same as Noto CJK.

**Comment by twinaphex** [comment]
Hi there, what is the status of this PR? Can this be merged?

**Comment by guoyunhe** [comment]
I saw @RobLoach approved this PR. Maybe @twinaphex you can merge this PR. And I will make a PR for RetroArch to support CJK fallback fonts.

**Comment by slankka** [comment]
There are still three problems, and solutions for fix:
```
Android version 1.9.12 Google Play
Devices: Honor V9
Theme: glui
```
according to my research:
1. changing assets/pkg/chinese-fallback-font.ttf will fix title bar and title “口 · 口”。
title tofu 2024-08-02 220602-ed

2. changing assets/ozone/bold.ttf will fix OSD toast character display issue.
toast-fix

3. changing assets/ozone/regular.ttf will fix game loading OSD title display issue.
image-run-loading

Hope it will help.

Currently the font defaults:
```
assets/pkg/chinese-fallback-font.ttf -> Droid Sans Fallback
assets/ozone/bold -> Inter UI Bold
assets/ozone/regular.ttf -> Inter UI
```

The font I'm using: Open Harmony Sans Sc.

**Pull request merged**
