### PR TITLE
New Dot-art theme.

### PR DESCRIPTION
**Pull request by Tatsuya79**
Removed Yoshi-kun theme.
Added readme and some naming corrections.

### CODE REVIEW

**Comment by twinaphex** [comment]
So dot-art is another name now for the yoshi-kun theme?

**Comment by Tatsuya79** [comment]
Yes, I thought that name makes more sense.

**Comment by RobLoach** [comment]
I tried this out, and find since the icons are 32x32 and expanded to 256x256, they end up looking pretty bad....

dot-art

**Comment by RobLoach** [comment]
> I thought that name makes more sense.

Why?

**Comment by twinaphex** [comment]
Yeah I guess for the bigger icons we need higher quality assets. I will merge this for now so that we have a base to work with.

**Comment by Tatsuya79** [comment]
@RobLoach 
Well, they're supposed to look like that as they are pixel-art. The additional shadow is perhaps not needed.
They look better while smaller.

The name is taken for [the Japanese term for pixel-art](https://github.com/libretro/RetroArch/pull/4534/files) to make a "bad translation"/confusion with dot-art in general (that's what pixel-art is after all).

**Comment by RobLoach** [comment]
Sounds like a good name change to me :+1:

**Pull request merged**
