### PR TITLE
Added and updated more core icons

### PR DESCRIPTION
**Pull request by Jaffacakelover**
Created and updated icons for all themes, for: Cannonball, Dungeon Crawl Stone Soup, Game Music Emu, Mr. Boom, PocketCDG, Rick Dangerous, RPG Maker, Sega - VMU, Sony - PlayStation 2, Sony - PocketStation, Star Trek Voyager - Elite Force, The Powder Toy, Uzebox.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
Pretty nice. :+1:

**Comment by twinaphex** [comment]
Hi there @natinusala ,

first of all, merry Christmas. When you have some time, would you like to review this PR since it touches a lot of assets in Ozone? @Tatsuya79 gave it his thumbs up already but I'd like to hear your feedback too.

**Comment by natinusala** [comment]
Hi @twinaphex merry Christmas to you too !

I looked at the changes and it looks good to me, I assume @Jaffacakelover added the SVGs and executed the script to generate the PNGs?

**Comment by Jaffacakelover** [comment]
I added the SVGs, but didn't use a specific script for the PNGs. I might have put some through TinyPNG. Could someone point me in the direction of this script if needed?

**Comment by natinusala** [comment]
It should be somewhere in the repo, in the XMB folder I think? Just run it 
and it will convert and optimize everything using the right settings

You should use it because it's how we make the other PNGs, so if you don't 
make sure it works your images will be overwritten by someone else by 
mistake when running the script eventually.

Le 26 décembre 2020 17:49:53 Jaffacakelover <notifications@github.com> a 
écrit :

**Comment by Jaffacakelover** [comment]
I've been struggling for days to try and get that .sh script to run on Windows.
I've installed MSYS2 and Inkscape, both are assigned to system paths for all users, and yet:

`line 22: inkscape: command not found`

screenshot 1609858225

Any ideas? Wrong syntax in my commands? Inkscape looking in the wrong folder for its system path?
I'm gonna write up some proper instructions once we crack this!

**Comment by natinusala** [comment]
Uhhh I have no idea if using MSYS2 works, I don't know if the Windows version of Inkscape supports CLI, probably not ?

Nevertheless you should run the script in the repo using real UNIX paths and not /d/something/script.sh, like you would on Linux (cd in the folder and ./something/script.sh).

**Comment by Jaffacakelover** [comment]
Tried `$ cd d:Github/retroarch-assets/xmb/`, then `convert.sh`, `sh convert.sh` and [bash convert.sh](url) after that, same error.
Maybe I've goofed somewhere. Maybe it doesn't support it. I should dig out my old Pi/VM and give it a go on there, see if anything changes.

**Comment by natinusala** [comment]
Does the Inkscape command work inside of MSYS2?

**Comment by Jaffacakelover** [comment]
Capture1
Doesn't look like it.

**Comment by natinusala** [comment]
What happens if you do pacman -S inkscape ?

**Comment by baxysquare** [comment]
Is this a script we should actually be using?  I wasn't sure if it was outdated.

Because my source files are Adobe Illustrator PDFs instead of SVG files, my workflow is a bit different. I use [a PDF to SVG script](https://forums.libretro.com/t/neoactive-retroactive-and-systematic-theme-support-and-feedback/9501/19) from @alfrix and then the following Image Magick commands to create the PNG files.  Once that's done, I throw them into ImageOptim before submitting the 256 versions for a PR.

`64/sd - prep for #341
_magick mogrify -background 'rgb(255,255,255)' -alpha Background -density 72 -resize 25% -format png *.pdf_

128/hd - prep for #341
_magick mogrify -background 'rgb(255,255,255)' -alpha Background -density 144 -resize 25% -format png *.pdf_

256/4k - currently submitted
_magick mogrify -background 'rgb(255,255,255)' -alpha Background -density 288 -resize 25% -format png *.pdf_

512/8k - prep for #341
_magick mogrify -background 'rgb(255,255,255)' -alpha Background -density 576 -resize 25% -format png *.pdf_

1024/16k - prep for #341
_magick mogrify -background 'rgb(255,255,255)' -alpha Background -density 1152 -resize 25% -format png *.pdf_
`

**Comment by natinusala** [comment]
Well most XMB and ozone icons use that script so I would rather streamline 
the process and use it for everything.

Ultimately we would like to remove the PNGs from the repo altogether and 
have the new CI infra build them from the SVGs when needed.

**Comment by baxysquare** [comment]
I'm supportive of using one script and streamlining the process.  It's what we're trying to do over on #341 and I'm guessing that script will be a keystone of that effort.  I prefer the results of ImageMagick over Inkscape, so I would recommend it at least be considered for the script, if it hasn't been already.

**Comment by Jaffacakelover** [comment]
I work in Illustrator with SVG files, then export them as PNG. Shall I run the files from this pull request through ImageOptim for now?

**Comment by m4xw** [comment]
For the new infra we strongly prefer to have them SVG only (at least after the steps were added to .gitlab-ci.yml)
Platforms that want them grinded (vita, 3ds), that is already automated for png's (here we will just feed the images from the earlier step)
This will be locally provided to the runners
I don't mind having the PNG's for now as well, but this should all get squashed out of the commit history going forward.
(We'd only want it *highest* quality tho, if theres no SVG available)

@baxysquare as for the used tools, as long its available for a linux distro, you have the artistic freedom to pick whatever you prefer / produces the best results

**Comment by Jaffacakelover** [comment]
In which case I'll leave this pull request as is (they've been through TinyPNG already), and leave you to sort all these "objectives" comments into their own thread!

**Comment by natinusala** [comment]
The thing is that once we jump to the new environment we won't be able to reproduce the PNGs you sent since you did not provide a script to go from SVG to PNG. We'll be able to recreate them but not exactly

**Comment by Jaffacakelover** [comment]
But this branch includes the SVGs too...

**Comment by baxysquare** [comment]
@ natinusala I'm understand and I'm comfortable with that tradeoff in order to further the greater good.  It should make submitting a theme author's PR much easier since all that should be needed are the SVG files.  It also paves the way for @jdgleaver to implement the Universal Theme format (#341), bringing the theming capability to other UIs, rather than leaving them trapped on XMB.

**Comment by natinusala** [comment]
> But this branch / pull request includes the SVGs too...?

Without an automated way to generate the PNG from the SVG it's less ideal, it's like providing the source code of a program without the makefile (so to speak)

**Comment by Jaffacakelover** [comment]
Then I'm afraid you've lost me. This PR has the source SVG files, and the exported/compressed PNG files. Meanwhile, a shell script to convert SVG to PNG is included on the master repo.

**Comment by natinusala** [comment]
> Meanwhile, a shell script to convert SVG to PNG is included on the master repo.

But you failed to make it work on MSYS2 with your files, am I mistaken? If you did not test it we don't know how the script behaves with your images.

The PR is fine as it is, you can go ahead and merge it, it's just that while you are here might as well take care of the script for the time being, while we wait for the new system to come out.

**Comment by Jaffacakelover** [comment]
I've set up Ubtuntu in a VM, cloned my branch in via GitKraken, and run the script in the folder... I STILL can't get it to work.

Capture


If this becomes a mandatory rather than a 'nice to have' step, this need to be made a platform agnostic process going forward.

**Comment by m4xw** [comment]
did you do chmod +x  convert.sh ?

**Comment by Jaffacakelover** [comment]
...my word, I think that worked! The modified date on the file has changed... although it complains about a missing package.

Capture3

**Comment by natinusala** [comment]
Making it platform agnostic is a good point, however I don't know if it's possible given the lack of a sane inkscape CLI on Windows 😕 But I'm happy to see that you made it work!

**Comment by fpscan** [comment]
@Jaffacakelover Hi,

Maybe we can revisit this PR? Would like to make new one or solve the conflicting files? Then we can ask natinusala for their inputs as well.

**Comment by Jaffacakelover** [comment]
@fpscan I can certainly restart work on this project - as you can see above, it mainly got held up by a larger discussion over image compression and future format considerations.

I don't have the powers to resolve this conflict myself, but I present the below:

- dot-art: The master (left) has xmb monochome assets with a black outline applied. My branch (right) has pixel art to match the theme style.

conflict-dot-art

- Systematic: I've removed my PocketStation files, as they're duplicates of one for the retrosystem theme.
- Systematic: Is the master (left) VMU copied from Retroactive? I can't decide on this one.

conflict-systematic

**Comment by baxysquare** [comment]
@Jaffacakelover It looks like we were working over the top of each other.  Up until this point I've been the only contributor for Systematic, Automatic, Retroactive and NeoActive.  I'm not opposed to other contributors, but **I prefer to encourage artists and designers to try and make their own full theme.**  It's really not that difficult, but it is very fulfilling when your set is rolled out as an option for people to choose.  It should only get better once [unified themes are rolled out](https://github.com/libretro/retroarch-assets/issues/341), making it so they can be enjoyed outside of XMB.  **I really think you have what it takes to make your own theme end-to-end.  You should give it a shot!**

The VMU and PocketStation for Systematic and Retroactive are currently identical.  This is quite common for these two themes.  Retroactive is meant to use the controller as the primary icon, while Systematic uses the system hardware.  Since most portables and some other platforms are both the system hardware and the controller, there's no reason to design a second icon.

My intention is to fully support Systematic and Automatic. I'm looking to retire and remove NeoActive, unless someone really likes it and wants to take it over. I'm currently working to [merge Retoactive and FlatUI into a single theme](https://github.com/libretro/retroarch-assets/issues/17) by recoloring the entire Retroactive set with an expanded FlatUI palette.  I had also planned on contributing a bunch of missing icons to Monochrome, but I had a drive crash and lost a fair amount of work.  It's something I intend to get back to, but needed to work on something else to put that data loss behind me.

**Comment by Jaffacakelover** [comment]
That's what I set out to do here: Happy to be contributing a bunch of missing icons to existing sets, not creating a brand-new set. I can leave "your" sets (Systematic, Automatic, Retroactive and NeoActive) alone until the stated merges / deletions are done? I could stick to fleshing out Monochome / Dot-Art for a while?

**Comment by baxysquare** [comment]
I'm super impressed with your contributions and would seriously urge you to consider making your own theme.  I totally understand why you prefer to contribute.  But you have the talent and the skill to contribute a full theme, and I think the project would benefit greatly by having at least one full "theme by @Jaffacakelover." :-)

Feel free to do whatever you'd like to NeoActive.  I'm absolutely finished with it and I'm ready to delete it from the project.  The art style never worked quite the way I intended and I feel it's the worst theme in the whole project.  If someone wants to take on that theme and redo it however they want, they have my blessing.

I intend to rebrand RetroActive as "FlatUX" and I will be proposing that it completely replaces FlatUI and RetroActive.  So I'd steer clear on that theme, until after it goes live.  For me the focus has been to recolor the RetroActive set exclusively.  But from there, anyone who wants to contribute to that theme, will be encouraged to do so.  There will be plenty of opportunity to merge FlatUI's style into FlatUX by adding flare to the individual icons, as well as adding missing icons to the set.

As for Systematic and Automatic, people are welcome to contribute, but I reserve the right to go through and adjust the artwork to be consistent with the rest of the set.  I don't want to step on toes but I also want to make sure there's continuity and uniformity within the full themes.

**Comment by Jaffacakelover** [comment]
Reorganizing into new branch/pull request

**Pull request closed without merging**
