### PR TITLE
Add OSD font

### PR DESCRIPTION
**Pull request by alfrix**
Patched version of DejaVuSans Condensed with the following glyphs:

🏆⏩ ⏪ ⏫ ⏬ ⏭ ⏮ ⏯ ⏴ ⏵ ⏶ ⏷ ⏸ ⏹ ⏺

@RobLoach Reopen #5710

### CODE REVIEW

**Comment by alfrix** [comment]
captura

**Comment by RobLoach** [comment]
@alfrix Didn't seem to work with the attached patch: [`forward.diff`](https://github.com/libretro/retroarch-assets/files/1492249/forward.txt).

It's on top of my `osd-font-assets-dir` branch:
https://github.com/robloach/retroarch/tree/osd-font-assets-dir

screenshot at 2017-11-21 11-59-18

Could you test?

**Comment by RobLoach** [comment]
Fixed it!
screenshot at 2017-11-21 12-13-40

**Comment by RobLoach** [comment]
@alfrix @fr500 brought up https://github.com/juliettef/IconFontCppHeaders , which may be a good idea.

**Comment by alfrix** [comment]
Interesting, could be a comfortable way to keep track of icons

**Comment by Alcaro** [comment]
Looks like #179 screwed up this one too. I'm just gonna call it a bug in GitHub.

Please rebase and open a new PR. Sorry for the inconvenience.

**Comment by RobLoach** [comment]
This OSD font may not be the right way around it. We may want to split the Icon different from the message. An icon is not translatable, it's the message that is.

**Comment by alfrix** [comment]
May not be the best, but at least it's something.
What if we concatenate the icon with the string in retroarch.c?

**Pull request closed without merging**
