### PR TITLE
Added Commodore 64 & Amstrad CPC, Minor Fixes

### PR DESCRIPTION
**Pull request by baxysquare**
- Added C64 (#131) & Amstrad CPC to Monochrome, NeoActive, RetroActive
& Systematic
- Added Xbox & PS2 icons to Monochrome & NeoActive
- Reloaded Monochrome contributions using smoother PNG files
- Fixed netplay icon for NeoActive, RetroActive & Systematic

### CODE REVIEW

**Comment by RobLoach** [comment]
Very nice! :+1:

**Comment by Kivutar** [comment]
Just one thing, for monochrome, the icons need to be not wider than the circle contained in the 256x256 square. This rule is there to ensure that all icons are similar in area. I saw that you changed the PCE CD icon, the Dinothawr icon, and some others. Please read this https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/README.md and rollback the changes on these icons.

**Comment by Kivutar** [comment]
I also notice that Dinothawr.svg contains just a PNG image, and not the source SVG. We can't keep it like this. It also affects Microsoft Xbox, Playstation 2, and other icons you added.

**Comment by baxysquare** [comment]
I forgot to add the SVGs when I uploaded.  Sorry about that.  They are already published on my GitHub but I'll add them to the SRC folder.  As for the the 256x256 square, I'm curious what you're seeing, as the icons should actually have a maximum size of 232x232 floating on the 256x256 canvas.  I'm guessing this may have to do with some issues with the fact that I use Adobe Illustrator instead of Inkscape.  I'll work on getting it fixed ASAP.

**Comment by Kivutar** [comment]
I pushed a few fixes

**Comment by baxysquare** [comment]
OK here's where I went wrong on monochrome... My workflow for my themes is Illustrator PDF and ImageMagick Mogrify.  For monochrome, I usually go to the effort of opening my Illustrator PDF in Inkscape, resizing the canvas, resizing the icon, saving the SVG and exporting the PNG.  

I'm was going to revert back the icons to the backed up ones, but I don't want to mess with your fixes.  Let me know how you'd like to proceed.

**Comment by RobLoach** [comment]
Thanks for all the updates, you two!

**Comment by baxysquare** [comment]
@Kivutar let me know if there's anything else I can fix.  I'm happy to upload new SVG and PNG files created in Inkscape from my source PDFs if you feel that will help above and beyond what you fixed.  I'm so sorry that in my haste I forgot a few steps on my monochrome contributions that it made more work for you.  As I contribute to the theme in the future, I'll make sure to go through the Inkscape process.

**Comment by Kivutar** [comment]
No problem! I still see a few things that doesn't match the guidelines, but nothing urgent.

**Comment by baxysquare** [comment]
In terms of the guidelines, I'm guessing the port icons like Dinothawr and Dungeon Crawl are the ones that are in largest need of improvement, especially in getting as many points aligned to the grid as humanly possible.  The system designs should be clean unless you feel my use of 2 pixel elements oversteps the guidelines too much.  When testing them in RA and Lakka, I don't mind the way they scale but I'm open to your suggestions.

Up until this point, I've tried to only contribute to Monochrome to bring the theme up to par with the audits on #71 and other requests such as #110.  I probably overstepped with the Amstrad, Xbox & PS2 and perhaps even the netplay batch. If you feel I've stepped over the line in terms of contributions, please let me know and we can delete them until you feel they're "ready for prime time."

**Comment by Kivutar** [comment]
I pushed a fix for the Dungeon Crowl one. When we include detailed drawings in the icon, it's impossible to align them on the grid.

The main problem we were facing when designing Monochrome was the very various style of the pads. Our first theme, FlatUI, was looking too inconsistent despite the unified palette. So we pushed the idea further and went for a single color, with super simplified yet identifiable shapes.

The grid alignment is useful when icons are downscaled at 0.5, 0.25, 0.125, especially on ARM where mipmapping is disabled.

The hyperellipse is also there to add consistency, especially when we have no choice but to use logos.

The amstrad keyboard is too detailed compared to the other icons in the set. But it's better to have it than a black square! I'm using it in the next version of Lakka.

The netplay icons don't fit the theme well either, because we usually limit the icon to a single shape, while the netplay icons are composed on many similar shapes linked together. So I used an icon inspired from the PS4 party icon (the headset) instead.

**Pull request merged**
