### PR TITLE
Move the optimized images

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by hyarsan** [comment]
I actually was going to do it myself first, sorry lol

**Comment by RobLoach** [comment]
Haha :+1:

**Comment by hyarsan** [comment]
So when you need to move a file you need to rename a file to *insert directory goal*/*the file* ?
The more you know :)

**Comment by hyarsan** [comment]
Oh, and here are the non-optimized original versions of the branding arts since the optimization was reverted. ( for the sake of consistency ) :
retroarch_bg
retroarch_libretro_bg

**Comment by RobLoach** [comment]
This makes the logo larger. Is it really something we want?

**Comment by hyarsan** [comment]
Larger as in file size? Well if every other asset is not optimized anymore, then I feel we should do the same thing. They might re-optimize it later on, so I don't think a wallpaper that is compressed two times is a good idea. The current "wallpapers" with the right path have the big logos. The one in the root directory would need to be replaced with the ones that I supplied above. I don't think we want the wallpapers with the logos to be slightly different in quality.

**Comment by RobLoach** [comment]
No, the logo at the bottom left. Try the Swipe comparison in files changed.

**Comment by hyarsan** [comment]
You mean bottom right? There is nothing at the bottom left corner. Alcaro reverted the optimization, so now it is bigger again. The point of the images I provided above is so that it could get smaller again, also without the optimization that Alcaro removed :)

**Comment by RobLoach** [comment]
You're right... It makes the RetroArch logo at the bottom right smaller. Here's a before after...

### Before

retroarch_bg

### After

retroarch_bg 1

I like the changes! :+1:  The logo looks sharper.

**Comment by twinaphex** [comment]
Alright, let's merge it then.

**Pull request merged**
