### PR TITLE
Added remaining Monochrome / Ozone icons

### PR DESCRIPTION
**Pull request by Jaffacakelover**
Lots of new Monochrome / Ozone icons, in SVG and PNG (compressed using Pinga).
Combined with #432, this should complete the to-do list in #433.

Thumbnail of all icons (click for full size):

Below are the icons that use logos (a concern raised in #432): A decision needs to be made if these need to be changed.
ones-with-logos

A few of the '-content' icons might be a bit small and need tweaking (such as 'Mobile-PalmOS-content').

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
For now those look fine. 

One small concern I have - all these files that are added with this PR, how many MBs does that add up to?

**Comment by Jaffacakelover** [comment]
- `#435` (this commit) = **2.15 MB** (2,259,328 bytes)
- `#432` = **0.5 MB** (517,388 bytes)
- `retroarch-assets` (2022-07-24, ozone & monochrome, png & src (not inc. ttf)) = **3.84 MB** (3,842,521 bytes)
- Above 3 combined = **6.62 MB** (6,619,237 bytes)
...
- `retroarch-assets` (complete repo 2022-07-24) = **613 MB** (643,236,521 bytes)

**Comment by baxysquare** [comment]
@LibretroAdmin We'd like to tackle the MB bloat issue caused by [retroarch-assets](https://github.com/libretro/retroarch-assets) through moving to a [Unified Theme format](https://github.com/libretro/retroarch-assets/issues/341) that will benefit all the UXs.  Part of that proposal is that SVG sources be required, and the PNG files in any needed size would be created by batch script.  The project is on the to-do list for @jdgleaver.

**Comment by hizzlekizzle** [comment]
jdgleaver is on indefinite hiatus / retired, so we probably shouldn't wait on him :P

**Comment by baxysquare** [comment]
@hizzlekizzle That's good to know.  That means we'll need some help getting it implemented as outlined in #345.  It's a worthy cause that would greatly benefit the main project.

**Pull request merged**
