### PR TITLE
Localized Monochrome On & Off Per #273

### PR DESCRIPTION
**Pull request by baxysquare**
Removed the words "On" and "Off from the icons.  Turned the circles to ovals and added a plus for on and a minus for off.

### CODE REVIEW

**Comment by bparker06** [comment]
I really don't like the look of this at all. @twinaphex did you approve this?

**Comment by Clutz450** [comment]
I personally don't like it either.  Is there possibly a way to add an option to change the way it looks so for those who want on/off can have that look and those who want +/- can have that look?  Kind of like how we can change the way the icons look for the different systems?

**Comment by baxysquare** [comment]
The retroarch-assets team is between a rock and a hard place on this one.  @RobLoach has a valid point that the previous version is bad for localization and less readable at lower resolution.  The only way we can address #273 on our own is with the icons submitted on #292.  

The most direct alternative solution would be to change the toggle from a set of two icons to a word set like "On" and "Off" like all the other menu settings.  I think that might be a cleaner solution, as it would provide the end user with an on and off setting in their native language.  But that would need to be changed within the code of the mainline project.

**Comment by Clutz450** [comment]
Does it have to be icons?  Like can we just have the words "enabled" or "disabled" located next to each option?  Then, when someone chooses their language in RetroArch those words will be translated to their selected language?  

The only other option I think would be better was something that @bparker06 had said in the RetroArch Discord.  He had posted a screenshot of how smartphones handle something similar in their settings.  Since almost everyone these days has a smart phone, I think mimicking this kind of on/off toggle would be recognized by many and understand what it means. 
screenshot_20190221-091526_settings

**Comment by baxysquare** [comment]
It does not have to be icons.  It should be able to be changed in the mainline libretro codebase to be words instead of icons.  We just need someone to make that change in the code and then we can remove the On and Off PNG and SVG files from the repository.

Technically, we can also change the icons by changing them back to circles and removing the plus and minus markings as you propose. Because the default theme is monochromatic, it doesn't have the benefit of indicating on and off like iOS via color and position, which is important for accessibility to the end user, from a design standpoint.  So I took a look at how classic monochrome macOS handled it.  Off was an outlined circle and on was a filled in circle inside the outlined circle.  

on_off_proposal3

**Comment by RobLoach** [comment]
I like "Current", and "Position Notification" ones you've mocked up. Using my expert design skills, how about a hybrid for Position and Position/Shape, like the one on the right?

offon

**Comment by baxysquare** [comment]
That solution would also give the user position and shape notification.  If the team wants to go the icon route, I'm in favor of either Position/Shape Notification or @RobLoach's Notification as a solution.   I'm also fine with going the text route if that's what the team would rather do.

**Comment by hizzlekizzle** [comment]
@baxysquare I spoke with the gang on discord and the consensus seems to favor @RobLoach's suggestion. Everyone agrees that it's simple and readable.

**Comment by Tatsuya79** [comment]
53199140-4c4a4300-35ec-11e9-983e-f7b1f9612d09

**Comment by twinaphex** [comment]
When can we expect this new replacement icon? 

We can't really ship 1.7.7 with the current icon.

**Comment by baxysquare** [comment]
@twinaphex I just submitted #294 but it was based on the feedback from @hizzlekizzle.  Do you want me to withdraw it and resubmit using @Tatsuya79's design?

**Comment by RobLoach** [comment]
I still feel like @Tatsuya79's design at https://github.com/libretro/retroarch-assets/pull/292#issuecomment-466702824 has too much happening.

I'd say roll with #294 and let's spark another conversation up about updating it from there. Just getting this update in will help unblock 1.7.7.

**Pull request merged**
