### PR TITLE
Optimize images (9.1MB reduction)

### PR DESCRIPTION
**Pull request by nvllsvm**
Used these commands:

    oxipng --zopfli --opt max --strip all
    jpegoptim --all-progressive --strip-all

### CODE REVIEW

**Comment by jdgleaver** [comment]
I'm not sure about the rest, but the RGUI wallpaper images in ` rgui/wallpaper` cannot be modified in any way. They are very specifically formatted for compatibility reasons.

**Comment by Tatsuya79** [comment]
Please no. 
Tools like that are destructive especially on the maximal opt setting.

It was already done several times in the past on more conservative settings.

**Comment by nvllsvm** [comment]
@jdgleaver 
> I'm not sure about the rest, but the RGUI wallpaper images in ` rgui/wallpaper` cannot be modified in any way. They are very specifically formatted for compatibility reasons.

I can remove these if needed.

What specifically is unique with the `rgui/wallpaper` images? 

@Tatsuya79 
> Tools like that are destructive especially on the maximal opt setting.

How so? They *shouldn't* be destructive on max settings. The only thing which could be problematic is this iteration's stripping of all metadata. I'll gladly rerun without any stripping if you'd like.

The main difference in this iteration is the use of the zopfli compressor.

**Comment by baxysquare** [comment]
All the icons for Automatic, Systematic, Retroactive and Neoactive were run through ImageOptim before submission.  I'm not quite sure if this is necessary for those themes.

**Pull request closed without merging**
