### PR TITLE
Add CC-BY-4.0 license, fix #15.

### LINKED ISSUE #15: Licensing assets
Hi!

Opening this issue to discuss what should be the best license for all these files. I created 2 or 3 icons for flatui, whatever you guys choose, I'm in.

Have in mind it should be compatible with RetroArch, which is GPL-3+

MIT, BSD, CC-BY ?

@Kivutar 
@Bibalox
@Niouby
@lollo78 
@twinaphex

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
@Bibalox
@Niouby

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
Guys, I really need this to properly package for debian, @Kivutar

**Comment by Bibalox** [comment]
Sorry guys, i’m quite busy those days.

Kivutar, Sergio, what to you expect me to do exactly ? I mean, how do I do I had the CC licence on Github ? I don’t want to mess with it.

Jean-Baptiste Bal
+33 (0) 6 52 13 24 39

29, allée des Deux Mondes
38100 GRENOBLE

**Comment by sergiobenrocha2** [comment]
@Bibalox, just say if you are OK with it :D 

well, it's merged already.

**Comment by Bibalox** [comment]
Haha, I’m fully ok with it ! We had to add a licence anyway and it seems to be the best solution.

Thanks Sergio.

Jean-Baptiste Bal
+33 (0) 6 52 13 24 39

29, allée des Deux Mondes
38100 GRENOBLE

**Pull request merged**
