### PR TITLE
Critical: Fix Arabic, Korean and Chinese fonts

### PR DESCRIPTION
**Pull request by guoyunhe**
Sorry, my previous PR #338 isn't up-to-date and it miss some files.

### CODE REVIEW

**Comment by leoxxx** [comment]
I'll test next lease.

**Comment by guoyunhe** [comment]
@leoxxx you can already test it today. Just update assets or re-install the app.

**Comment by leoxxx** [comment]
> 
> 
> @leoxxx you can already test it today. Just update assets or re-install the app.

The apk already update? I'll try it.

**Comment by guoyunhe** [comment]
No update to apk. When you re-install, it automatically updates assets.

**Comment by leoxxx** [comment]
> 
> 
> No update to apk. When you re-install, it automatically updates assets.

@guoyunhe 

Still need updates assets in 1.8.9.

**Comment by leoxxx** [comment]
Still need updates assets in 1.9.0

**Pull request merged**
