### PR TITLE
(Pixel) Add Munro as the Pixel font

### LINKED ISSUE #266: Font missing in the pixel theme?
When starting RetroArch with the current master with the pixel theme this is now printed.
```
$ retroarch
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
Failed to open /usr/share/games/retroarch/assets/xmb/pixel/font.ttf: No such file or directory
```
RetroArch will now print missing assets after PR https://github.com/libretro/RetroArch/pull/7681, but since the pixel theme is the only theme that seems to be missing `font.ttf` this is could be an issue with the theme?

### PR DESCRIPTION
**Pull request by RobLoach**
This enables [Munro](https://www.fontsquirrel.com/fonts/munro) as the font for the Pixel theme (SIL Open Font License). Having a font that aims to be readable in a low resolution environment matches the goals of the icons in Pixel.

pixel

Fixes #266

### CODE REVIEW

**Comment by orbea** [comment]
Looks fine to me.

For reference here is the current look without a font.

**Comment by RobLoach** [comment]
[Mozart NBP](https://www.fontspace.com/total-fontgeek-dtf-ltd/mozart-nbp) looks really cool too...

mozart

**Comment by RobLoach** [comment]
[Unifont](http://unifoundry.com/unifont/index.html) has the benefit of being translatable...

screenshot at 2019-01-06 14-32-36

**Comment by RobLoach** [comment]
Closing this for now. I18n is a PITA.

**Pull request closed without merging**
