### PR TITLE
Add yoshi-kun icon theme from Tatsuya79 from the forum

### PR DESCRIPTION
**Pull request by CoalaJoe**

### CODE REVIEW

**Comment by Kivutar** [comment]
Thank you

**Comment by CoalaJoe** [comment]
No problem. I help where I can :)

**Comment by Tatsuya79** [comment]
Thank you.

I thought about renaming the theme "dot-art" which is a bit more self-explanatory.

Also it doesn't cover every icons and won't be usable as is.
What I would do is paste them above a copy of monochrome if that's ok.

**Comment by CoalaJoe** [comment]
@Tatsuya79 Fork, download, change, push and then do a pull request.

**Pull request merged**
