### PR TITLE
rename MAME 2014 assets to MAME 2015 name

### PR DESCRIPTION
**Pull request by markwkidd**
This PR follows the merge of https://github.com/libretro/libretro-super/pull/940 which initiated the process. 

The PRs relevant to the name update are:
  * MAME 2014 repo: https://github.com/libretro/mame2014-libretro/pull/73
  * libretro-super repo: https://github.com/libretro/libretro-super/pull/942
  * libretro-database repo: ~~https://github.com/libretro/libretro-database/pull/787~~ Merged
  * retroarch-assets repo: https://github.com/libretro/retroarch-assets/pull/289

### CODE REVIEW

**Comment by ofry** [comment]
@markwkidd Please resolve merge conflicts.

**Comment by markwkidd** [comment]
@orfy OK, I have fixed the conflicts, thank you

**Comment by alfrix** [comment]
@markwkidd some of the icons have numbers in them, you can't just rename those, they have to be modified and re-exported

**Comment by markwkidd** [comment]
I'm seeing this message now after I earlier saw the PR to my personal repo and wrote there. Please let me know how you would like me to prefer to proceed.

**Comment by alfrix** [comment]
i sent the pr to your repo so it it will be correct without another pr

**Comment by markwkidd** [comment]
Thanks for helping me with this. I merged your PR but there are two conflicting files

**Comment by alfrix** [comment]
```
git remote add upstream https;//github.com/libretro/retroarch-assets
git fetch upstream
git rebase upstream/master
git add .
git rebase --continue
git push
```

**Comment by alfrix** [comment]
better use `git rebase -s ours upstream/master`

**Comment by markwkidd** [comment]
That added a lot of commits to this PR but it doesn't have any conflicts at least!

**Comment by markwkidd** [comment]
@alfrix I really appreciate your willingness to work with me on these submissions after I just showed up one day! I'm going to close this issue because I don't have anything else to offer that will fix my previous work or improve on what other folks have contributed.

In the future however as we add new games to MAME 2003-Plus I will probably open an issue here to coordinate with you on the thumbnails. There are already about 30-40 new games I need to add thumbnails for since my last update but I may wait till it's a few more before I go through that.

**Pull request merged**
