### PR TITLE
Add executable bit to script

### PR DESCRIPTION
**Pull request by tim77**
To make some linters happier.

### CODE REVIEW

**Comment by tim77** [comment]
Gently ping. Should be safe to merge.

**Comment by RobLoach** [comment]
This PR does a bit more: https://github.com/libretro/retroarch-assets/pull/444

**Comment by baxysquare** [comment]
@RobLoach do you think that #444 supersedes this PR?  If not, I'll go ahead and merge.  If so, I'll close and merge 444 instead.

**Comment by RobLoach** [comment]
> @RobLoach do you think that #444 supersedes this PR? If not, I'll go ahead and merge. If so, I'll close and merge 444 instead.

I'd vote to roll with #444 instead, yeah. It does what this issue does, and more.

**Comment by baxysquare** [comment]
Okay let's go ahead and close it and merge #444.  @tim77 if you have any issues with this course of action, feel free to reply to this issue and we'll go from there.

**Pull request closed without merging**
