### PR TITLE
Renamed Files & Cleanup

### PR DESCRIPTION
**Pull request by baxysquare**
To be consistent with No Intro, the following files have been renamed:

- "Bandai - Pippin" to "Apple-Bandai - Pippin"
- "Commodore - Amiga CDTV" to "Commodore - CDTV"
- "Nintendo Game Boy Advance (e-Cards)" to Nintendo Game Boy Advance (e-Reader)
- "Tiger Telematics - Gizmondo" to "Tiger - Gizmondo"
- "VM Labs - Nuon" to "VM Labs - NUON"
- "Handheld Electronic Game - GW" to "Nintendo - Game & Watch"

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I think we'll need the database entries for these renamed at the same time, right? @RobLoach

**Comment by baxysquare** [comment]
Based on what's listed at [db.libretro.com](https://db.libretro.com/), there is not currently a database for Pippin, CDTV, Gizmondo, or NUON. 

- There is a database called "Nintendo - eReader" that could be changed to "Nintendo Game Boy Advance (e-Reader)."  
- The "Handheld Electronic Game" would not be affected by this change.  It only affects the "easter egg" icons with a "GW" postfix.  They will simply be organized for the future, if "Nintendo - Game & Watch" gets a separate database.

**Comment by RobLoach** [comment]
Database list is currently... https://github.com/libretro/libretro-database/tree/master/rdb

Happy to help out with any renames. Just lemme know what needs to be renamed :+1:

**Comment by baxysquare** [comment]
Thanks's for pointing me to the GitHub RDB page.  I had no idea that [db.libretro.com](https://db.libretro.com/) was so far behind.  Are there plans to update it or make it forward to the Github page?

Changing all the "Amiga CDTV" to "CDTV" brings us inline with the RDB, so I think we're good to go on that one.  Pippin, Gizmondo and NUON don't have RDBs, but if they receive them in the future, it's probably beneficial to match them up with the No-Intro titles.  

E-Reader is a bit tricky.  The RDB is called "Nintendo - e-Reader.rdb" and we have icons in place that support that RDB that will not be affected by this PR.  But we also have a set called "Nintendo Game Boy Advance (e-Cards)" that will be renamed to "Nintendo Game Boy Advance (e-Reader)."  I have no idea if there's a need for both sets or exactly what should be done for this unique situation.  I'm open to suggestions.

Last but not least is Handheld Electronic Game. If you'd like to fork all the Game & Watch titles into an RDB that would use the same core as Handheld Electronic Game, I think people might appreciate it.  However, it may open things up the for more requests for segmentation for other brands like Tiger, Mattel or Coleco.  This PR is simply a means of potential future proofing, as "Handheld Electronic Game" and "Handheld Electronic Game-content" have not been affected.

**Comment by baxysquare** [comment]
I'm going to go ahead and merge this in the next day or two.  @hizzlekizzle and @RobLoach if you'd prefer I wait, let me know.

**Comment by hizzlekizzle** [comment]
I'll defer to RobLoach, since he knows all about the databases :)

**Comment by RobLoach** [comment]
Go to town! 😅

**Comment by RobLoach** [comment]
Let me know if there's any database that needs to be renamed. The .RDB are what they're named right now, could could be renamed.

**Pull request merged**
