### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by u1f35c**
These are a handful of minor cleanups I made while updating the Debian packaging for retroarch-assets.

 * Clean up executable permissions on data files
 * Remove duplicated scripts
 * Rename a source file to match the generated file base name

### CODE REVIEW

**Comment by baxysquare** [comment]
The majority of the files with permission issues are ones that I contributed.  I'm guessing the issue comes from the fact that the source files were created on a Mac.  Is there a command or script I should run to fix the permissions before I make contributions?

**Comment by u1f35c** [comment]
I ended up doing:

   * `find . -type f -name *.pdf -executable -exec chmod -x {} \;`
   * `find . -type f -name *.png -executable -exec chmod -x {} \;`
   * `find . -type f -name *.svg -executable -exec chmod -x {} \;`
   * `find . -type f -name *.txt -executable -exec chmod -x {} \;`

to make sure all those file types weren't executable (and a `find . -type f -executable` is useful for seeing all the executable files). I'd actually expected the issue to be more likely to have come from the Windows world than a Mac; I've no suggestion for how to avoid it on new files.

**Review by RobLoach — APPROVED** [review]
Looks like some good file permission fixes. Curious about the deletion of `xmb/convert.sh`? Is it implemented elsewhere?

**Comment by u1f35c** [comment]
`xmb/convert.sh` already exists as `scripts/xmb-convert.sh`

Rebased on top of current master to fix the merge conflict (some of the files with fixed up permissions have since been removed from the repo)

**Review by RobLoach — APPROVED** [review]
Thanks

**Pull request merged**
