### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by alfrix**

### CODE REVIEW

**Comment by alfrix** [comment]
Changed because of https://github.com/libretro/libretro-super/pull/640

**Comment by RobLoach** [comment]
Changing a lot of stuff here... Could you split it up into different PRs tackling each individual goal?

**Comment by alfrix** [comment]
what is the point in spliting? is something controversial or not allowed?

**Comment by RobLoach** [comment]
Nope, it just makes reviewing it a lot easier. Removing bg2? Chaning up xmb/retrosystem/png/Nintendo - Super Nintendo Entertainment System.png ?

I'd leave those changes to baxy or someone else with a design-y focus.

**Comment by alfrix** [comment]
bg2 is not used for anything, the user must go to the folder and rename it bg, if someone is willing to do that, they can grab it from systematic
and on the subject of the snes pad, if the nes pad is used as default, why not having a little consistency, i use some split playlist for the japanese games (J) and having different pads make it easier and nicer

**Comment by alfrix** [comment]
Satellaview and Sufami turbo also use the same pad, so not having them all equal makes sense to me

**Comment by alfrix** [comment]
@twinaphex thought on this?

**Comment by alfrix** [comment]
i'll split this up

**Pull request closed without merging**
