### PR TITLE
Remove WAV sound files

### PR DESCRIPTION
**Pull request by sonninnos**
Let's remove the space wasting WAV files from the package, since the frontend won't be using them, so it is enough that they only exist in `src`.

### CODE REVIEW

**Comment by baxysquare** [comment]
I agree that we don't need duplicates, but where the files should go permanently is up for debate.  Once upon a time, there was a proposal to [implement universal themes and clean up the repository](https://github.com/libretro/retroarch-assets/issues/341).  The idea is that common UI elements such as fonts, scripts, sounds, dev tools and cfg files would have their own directories in `root`, instead of being in the `src` directory, at all.  

However, the proposal was never all the way implemented and development stalled.  I'd love to see it happen, as I feel like all the UXs would benefit from having access to the themes, ultimately benefitting all users, instead of being limited to XMB.

**Comment by sonninnos** [comment]
Not sure how that is relevant to the sounds, since they are not tied to the menu driver. And ultimately it does not really matter where the raw source files are as long as they are not included in the redist package.

And I also don't get how anything is limited to XMB currently, since all menu drivers have their own assets, and obviously can't use other menu driver assets directly, other than icons of course, which are a bit of a mess since Ozone is using one certain XMB theme icons mostly.

**Comment by baxysquare** [comment]
I've never worked with the sounds so I have no idea why any sound files are hosted on this repository.  My guess is, at one point, they were intended for, but never used in XMB.  But that's pure conjecture on my part, as they've been here before I began contributing back in 2017.  If they have no relevance, I say delete them in both `sounds` and `src` unless there are plans to someday implement them for menu driver(s).  I'm all for reducing the clutter and only having what needs to be in this repository.

Nothing is directly limited directly to XMB, but all the XMB themes were effectively "buried" once Ozone became the default menu driver. The idea behind unified themes is that menu drivers would not have their own assets.  Every menu driver would instead have access to all the theme directories. 

Your point about Ozone being messy is exactly the problem I was hoping to solve with unified themes. Instead of organizing by menu driver, we'd organize by theme, with each theme having a dedicated directory with theme specific items.  For more common shared elements, they would have their own directories separate from the theme. 

As it stands, there's a lot of duplication and bloat in the repository.  Anything we can do to reduce the overall footprint by eliminating redundancies in the codebase, I am 100% in favor of.

**Comment by sonninnos** [comment]
Those oggs are very much used once you enable "menu sounds". Most of the assets are already pretty much organized.

**Comment by baxysquare** [comment]
Good to know on OGG menu sounds.  In that case, is there really a point in having the WAV files in the repository at all?  I saw the script in `/src/sounds/` to convert WAV to OGG.  If they are converted as part of compiling, it makes sense to keep them around.  If not, then should they go?

I'd love to continue discussing it on #341.  To quickly answer your question, the menu drivers need to be updated to support themes. 

I'm happy to merge the PR in about a week, if that's okay.  That will give anyone who wishes to chime in, the opportunity to do so.

**Comment by hizzlekizzle** [comment]
as long as the WAV files are safely stored *somewhere*. We don't want to lose our originals. There's no need in storing them here, specifically, though.

**Comment by baxysquare** [comment]
The WAV files will continue to exist in `/src/sounds/` for now.  At some point, they may come back to `/sounds/` if we decide to redistribute the files in directories at `/ ` and rearrange locations for all the items in `/src/`.

**Comment by sonninnos** [comment]
Indeed now `assets.zip` finally dropped from ~112 megabytes to ~93 due to this change. Not a huge lot, but at least something in the long run, and especially considering it was pure hot air.

**Pull request merged**
