### PR TITLE
Updated On & Off Icons Per #273 and #292

### PR DESCRIPTION
**Pull request by baxysquare**
As discussed, the on and off switch set has been updated for Monochrome, Automatic, Systematic, Neoactive and Retroactive.

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks like monochrome's off is missing a line...

https://github.com/libretro/retroarch-assets/blob/622fcfe3203314b3eec4b6cdaa22f0111a287b6b/xmb/monochrome/png/off.png

**Comment by RobLoach** [comment]
Looks great! What does your designer-eye think? Because I'm not a designer.

screenshot at 2019-02-25 18-49-53

**Comment by orbea** [comment]
Looks good to me as well.

**Comment by RobLoach** [comment]
Here's that alt you just upped. I kinda like it! Happy with either :+1: 

screenshot at 2019-02-25 19-10-56

**Comment by orbea** [comment]
I think the first one looks better, but either way is fine really.

**Pull request merged**
