### PR TITLE
RGUI Theme

### PR DESCRIPTION
**Pull request by fpscan**
@jdgleaver Hi, this is all good now :)

### CODE REVIEW

**Comment by fpscan** [comment]
There is also invade logo for branding, which I was discarded for anorher PR but if its need to remove I would like to remove

**Comment by jdgleaver** [comment]
@fpscan Yes, this is fine! Good work :)

**Comment by fpscan** [comment]
image
image
image

mostly shadow effect is on

**Comment by fpscan** [comment]
> @fpscan Yes, this is fine! Good work :)

thank you :)

**Pull request merged**
