### PR TITLE
Add monochrome_pixel - A jagged/pixelated version of monochrome with no wallpapers.

### PR DESCRIPTION
**Pull request by lasers**
The pixel theme is not completed and some icons requires to be pixelated first... meaning nobody really can use pixel theme right now... At least not without seeing polished icons.

I made a slightly pixelated version of monochrome along with two wallpapers (classic + full) for myself. Maybe we can have rgui options in xmb to generate proper checkered pattern. :smile:

### CODE REVIEW

**Comment by Kivutar** [comment]
Hello, we already started an effort like this, for Gamegirl. It is in xmb/pixel/png

**Comment by lasers** [comment]
Is it still an ongoing process? I'm seeing some polished icons (discs, Sony controller, etc). Maybe you can look at some of the files to help you speed up the process? I'm including the comparison. The wrenches might be too hard to see there.

320x240__0
320x240__1
320x240__2
320x240__3

I didn't make this for gamegirl. I made this to see retro bits everywhere instead of polished bits if that makes any sense. :sweat_smile:

**Comment by Kivutar** [comment]
On my screen, pixel looks like this:

capture du 2016-04-30 22-38-06
capture du 2016-04-30 22-38-17
capture du 2016-04-30 22-39-13
capture du 2016-04-30 22-39-37
capture du 2016-04-30 22-39-58
capture du 2016-04-30 22-40-28

**Comment by lasers** [comment]
Just discovering that I might mix up the directories (rgui-90, rgui-900, rgui-9000) so my screenshots might be bad. I will compare things using your layout. I thought we're doing actual 320x240. I didn't know RetroArch would resize internally (I think).

**Comment by Kivutar** [comment]
Also, try to have your icons to be 256x256 even if it looks useless, it will make them look not blur on big resolutions, because that's how the code works currently.

**Comment by twinaphex** [comment]
@Kivutar should we merge this?

**Comment by lasers** [comment]
Ready when you are. There is a bg.png in monochrome. RetroArch should load that too if `menu_wallpaper` isn't set. The images are now 256x256.

**Comment by Kivutar** [comment]
@lasers you're really sure there this is not duplicate work with the pixel theme?

**Comment by lasers** [comment]
Yes. Everything comes `monochrome` directory minus `bg.svg`.
Inkscape + imagemagick to make them pixelated.
RetroArch + Screenshot + GIMP = Two rgui wallpapers.
_(Waiting on a toggle for rgui classic mode in the future!)_

That's it. Nothing to do with pixel.

**Comment by lasers** [comment]
RGUI wallpapers omitted. Monochrome_pixel is an accurate way to identify this icons. Ready to go out if you approve this. @Kivutar

**Comment by lasers** [comment]
@Kivutar Should I go ahead and rename it really quick? I feel that using "monochrome_jagged" would reflect the icons more accurately in the long run than "monochrome_pixel"

**Pull request merged**
