### PR TITLE
Optimize all the PNG files (average of 76% reduction)

### LINKED ISSUE #116: PNG files are not optimised
/retroarch/media/xmb file size

for 1,541 items

3ds cia build:
2,976,106 bytes

after optimisation with ImageOptim ([settings](http://imgur.com/a/4muB6)):
2,061,461 bytes

### PR DESCRIPTION
**Pull request by alfrix**
This makes theme changing noticeably faster and may help platforms with limited storage.

I couldn't detect any noticeable changes in quality but theme makers should double check
@baxysquare 
@Kivutar 
@Tatsuya79 
@rutantan 

Commands used (also stated in the commit)

_pngquant.exe --skip-if-larger --quality=70-85
pngquant.exe --skip-if-larger --ordered --speed=1 --quality=70-90
optipng.exe -o=7_

## This resolves #116

### CODE REVIEW

**Comment by alfrix** [comment]
Just for the record the affected files reduced from 32 MB to 7.71 MB

**Comment by Tatsuya79** [comment]
I checked some pics from the dot-art theme and I see some loss of details and added dithering.
So I'm against it for that theme.

**Comment by fr500** [comment]
I think any destructive process should be done at build time for the specific platform. Not on the repo.

**Comment by alfrix** [comment]
Ok what about just using OptiPNG which should be lossless
_PNG optimizer that recompresses image files to a smaller size, without losing any information._

**Comment by baxysquare** [comment]
I have been optimizing via ImageOptim upon request in issue #116.  I'm not sure if there's any benefit to re-run them through OptiPNG.

**Comment by alfrix** [comment]
OptiPNG only saves the file if it's smaller and in some of your icons it did, look at the bottom of:
https://github.com/libretro/retroarch-assets/pull/171/files

**Comment by alfrix** [comment]
OptiPNG only saves the file if it's smaller and in some of your icons it did, look at the bottom of:
https://github.com/libretro/retroarch-assets/pull/171/files

**Pull request closed without merging**
