### PR TITLE
Added 5 variants of MageBoy Color rgui theme

### PR DESCRIPTION
**Pull request by efylan**
Pull request for adding MageBoy Color theme. Posted this as Matilda color theme in reddit

### CODE REVIEW

**Comment by fpscan** [comment]
@jdgleaver Hi Jdg,

I thought you would like to see/review this theme

**Review by fpscan — APPROVED** [review]
It's a beautiful theme for RGUI and I'm sure everyone will like it.

**Comment by jdgleaver** [comment]
These themes are lovely!

Really nice work :)

**Comment by fpscan** [comment]
Hi @efylan ,

If you happy with result and done with changes, we can inform Autechre so he can merge the pr :)

**Comment by efylan** [comment]
> Hi @efylan ,
> 
> If you happy with result and done with changes, we can inform Autechre so he can merge the pr :)

Yeah! I think I'm happy with the themes :P I mean I could add a loooot of color combinations but then I will never be done haha

**Comment by efylan** [comment]
Okay now I'm -really- done with the themes haha...

**Pull request merged**
