### PR TITLE
adds icons to dot art that wasnt present

### PR DESCRIPTION
**Pull request by kcin2001**
also replaces the netplay, images, history, and sattelaview content icons

a pr was requested im willing to make modifications upon request
https://forums.libretro.com/t/additions-to-the-dot-art-theme/15413

### CODE REVIEW

**Comment by Tatsuya79** [comment]
I'm against it.
It lacks uniformity, scaling and design wise.

**Comment by kcin2001** [comment]
tatsuya theres a huge disconnect between the icons you made and the game icons meanwhile most of my icons are taken from the same source as the game icons

**Comment by Tatsuya79** [comment]
I don't see the logic there, but you can make your own theme.

**Comment by kcin2001** [comment]
im unhappy with the battery and favorites heart icon, i will happily take any reccomendations to replace those

**Pull request closed without merging**
