### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hi! I'm ImgBot. Nice to meet you. 

I noticed there were a bunch of images living in your project that weren't totally optimized so I thought I'd make you a PR ;) I use a lossless compression algorithm from [ImageMagick](https://github.com/dlemstra/Magick.NET) so all the images are the same quality and dimensions as before only they take up less space now. 

Image processing is tough work, I know, but I never get tired and I never rest - not until all the images on GitHub are totally optimized.

*Total -- 6,521.39kb -> 5,248.69kb (19.52%)

/branding/retroarch_bg.png -- 3,259.45kb -> 2,620.36kb (19.61%)
/branding/retroarch_libretro_bg.png -- 3,261.95kb -> 2,628.33kb (19.42%)

### CODE REVIEW

**Comment by hyarsan** [comment]
Here's the thing, there is already a pull request to optimize it but even more :/

**Comment by RobLoach** [comment]
Thanks! :cl: :o: se

**Comment by RobLoach** [comment]
This can be closed.

**Comment by baxysquare** [comment]
Per @RobLoach's recommendation and the fact that this PR has been sitting for over two years, I'm going to go ahead and close it.  If you have any issues, please feel free to respond in this thread.

**Pull request closed without merging**
