### PR TITLE
Optimize Monochrome

### LINKED ISSUE #63: Monochrome Inconsistency
monochrome/src/\*.svg: 166 files
monochrome/png/\*.png: 171 files

Duplicate SVG files...
```
./Microsoft - MSX.svg
./Microsoft - MSX2.svg
./Atari - ST.svg

./Bandai - WonderSwan-content.svg
./Bandai - WonderSwan Color-content.svg

./Game-content.svg
./default-content.svg
./core.svg

./Sinclair - ZX Spectrum +3-content.svg
./Sinclair - ZX Spectrum-content.svg
./Sinclair - ZX 81-content.svg

./Microsoft - MSX2-content.svg
./Microsoft - MSX-content.svg

./SNK - Neo Geo Pocket Color-content.svg
./SNK - Neo Geo Pocket-content.svg

./Nintendo - Satellaview-content.svg
./Nintendo - Super Nintendo Entertainment System.svg

./NEC - PC Engine - TurboGrafx 16-content.svg
./NEC - PC Engine SuperGrafx-content.svg

./default.svg
./Game.svg

./NEC - PC Engine - TurboGrafx 16.svg
./NEC - PC Engine SuperGrafx.svg

./Bandai - WonderSwan.svg
./Bandai - WonderSwan Color.svg

./Nintendo - Game and Watch.svg
./Game and Watch.svg

./Nintendo - Nintendo DS.svg
./Nintendo - Nintendo DS Decrypted.svg

./Commodore Amiga-content.svg
./Atari - ST-content.svg

./Sega - 32X.svg
./Sega - Mega Drive - Genesis.svg

./FB Alpha - Arcade Games-content.svg
./MAME-content.svg
./MAME2003-content.svg
./MAME2010-content.svg

./Sega - Saturn-content.svg
./NEC - PC-FX-content.svg
./Neo Geo-content.svg
./Sony - PlayStation-content.svg
./wifi.svg

./Nintendo - Nintendo DS Decrypted-content.svg
./Nintendo - Nintendo DS-content.svg

./SNK - Neo Geo Pocket.svg
./SNK - Neo Geo Pocket Color.svg
```

Most likely to be missing duplicate SVG files...
```
Only in monochrome/png: NEC - PC Engine CD - TurboGrafx-CD-content.png
Only in monochrome/png: NEC - PC Engine CD - TurboGrafx-CD.png
Only in monochrome/png: Nintendo - Sufami Turbo.png
Only in monochrome/png: Sega - Mega-CD - Sega CD-content.png
Only in monochrome/png: Sega - Mega-CD - Sega CD.png
```

What's the play here for SVG directory? Seed it with more duplicate files? I assume symbolic links does not work on all platforms so do we keep it or remove duplicate SVG files to reduce some bandwidth? Add couple of lines in the script to copy few pngs from one SVG for few games? The ball is in your court.

There are probably more like that in other themes too. Should we configure something to keep src out of the assets.zip so the users does not download duplicate+duplicate assets? https://github.com/libretro/retroarch-assets/issues/24

### PR DESCRIPTION
**Pull request by lasers**
Fixes #63

### CODE REVIEW

**Comment by twinaphex** [comment]
@kivutar I'll leave it to you to merge this.

**Comment by Kivutar** [comment]
Hello, the SVG duplicates are needed

**Comment by lasers** [comment]
@Kivutar What should I do with this? Close?

**Comment by twinaphex** [comment]
Guess we'll close it.

**Pull request closed without merging**
